### ISSUE TITLE
how do i do parsing in PLY of the expressions containing SET Operators (UNION/INTERSECT/MINUS) and function calls?

### ISSUE THREAD

**Issue by nikitagupta55** [dabeaz/ply#149] opened 2018-02-05 02:24 UTC
I have to do Lexing and Parsing using PLY. So, my expressions can look something like below :

1.) (func1(b) INTERSECT func1(c)) UNION func2(a)
2.) func3(func1(b)) MINUS func1(d)

a,b,c are some names on the basis of which list will be returned from the fucntions func1,func2,func3

I have figured out the grammar rules, they will be something like below:

expression -> expression OP expression
expression -> func1(variable) OP expression | func2(variable) OP
                        expression | expression | func3(variable) OP expression
expression -> func1(expression) | func2(expression) | func3(expression)
expression -> (expression)
variable -> String
OP -> UNION | INTERSECT | MINUS (or we can use python symbols instead which can be |(union) | & | - )

Below is how basic lex.py code look like :

import ply.lex as lex
**1.) What should i declare in tokens so that my functions in the expression are identified correctly?** (func1,func2,func3) ? Below is how we declare tokens in lex.py

 tokens = (
       'LPAREN',
       'RPAREN',
       'INTERSECT',
       'UNION',
       'MINUS',
    )
2.) **What should i declare in regular expressions part so that my INTERSECT,UNION and MINUS and functions are identified correctly?** Below is how we declare tokens in lex.py?

t_LPAREN  = r'\('
t_RPAREN  = r'\)'

def t_newline(t):
    r'\n+'
    t.lexer.lineno += len(t.value)

t_ignore  = ' \t'

def t_error(t):
    print("Illegal character '%s'" % t.value[0])
    t.lexer.skip(1)

lexer = lex.lex()

**The role of the functions in my expressions is that, they will return a "list" and then the intersection/union/minus etc will be done on returned lists.**

**How do I write my lex.py so that my functions, parantheses and UNION/INTERSECT/MINUS operations are identified correctly?**

I'm trying to look for examples of PLY which does these sort of things, but i end up finding with normal +/- arithmetic operations code.

Please help me to find the solution for this type of case.

**Comment by ponyatov** [comment] 2018-02-06 05:29
```
class SYM:
    def __init__(self,T,V):
        self.tag = T ; self.val = V
        self.nest=[] ; self.attr={}
    def __repr__(self): return self.dump()
    def head(self): return '<%s:%s>'%(self.tag,self.val)
    def pad(self,N): return '\n'+'\t'*N
    def dump(self,depth=0):
        S = self.pad(depth)+self.head()
        for i in self.attr:
            S += ',%s = %s'%(i,self.attr[i])
        for j in self.nest:
            S += j.dump(depth+1)
        return S
    def __lshift__(self,o): self.nest.append(o) ; return self

import ply.lex  as lex
import ply.yacc as yacc

tokens = ['OP','LP','RP','ID']

t_ignore = ' \t\r\n'

def t_error(t): raise SyntaxError(t)
def p_error(p): raise SyntaxError(p)

def t_LP(t):
    r'\('
    return t
def t_RP(t):
    r'\)'
    return t

def t_OP(t):
    r'INTERSECT|UNION|MINUS'
    t.value = SYM(t.type,t.value) ; return t

def t_ID(t):
    r'[a-zA-Z0-9_]+'
    t.value = SYM(t.type,t.value) ; return t
    
def p_REPL_none(p): 'REPL : '
def p_REPL_recur(p):
    'REPL : REPL ex '
    print p[2]
def p_ex_OP(p):
    'ex : OP'
    p[0] = p[1]
def p_ex_FN(p):
    'ex : ex LP ex RP '
    p[0] = p[1] << p[3]
    p[1].attr['type']='function' ; p[3].attr['parameter']=True
def p_ex_BINOP(p):
    'ex : ex OP ex '
    p[0] = p[2] << p[1] << p[3]
def p_ex_PARENS(p):
    'ex : LP ex RP '
    p[0] = p[2]
def p_ex_ID(p):
    'ex : ID'
    p[0] = p[1]

lexer = lex.lex()

syntax=yacc.yacc(debug=None,write_tables=None)
syntax.parse('''
    (func1(b) INTERSECT func1(c)) UNION func2(a)
''')
syntax.parse('''
    func3(func1(b)) MINUS func1(d)
''')

```

**Comment by ponyatov** [comment] 2018-02-06 05:43
In result you will get parsed data in AST tree form:

```<OP:UNION>
	<OP:INTERSECT>
		<ID:func1>,type = function
			<ID:b>,parameter = True
		<ID:func1>,type = function
			<ID:c>,parameter = True
	<ID:func2>,type = function
		<ID:a>,parameter = True```
```<OP:MINUS>
	<ID:func3>,type = function
		<ID:func1>,parameter = True,type = function
			<ID:b>,parameter = True
	<ID:func1>,type = function
		<ID:d>,parameter = True```

**Comment by nikitagupta55** [comment] 2018-02-06 05:45
Would I mind giving some explanation of the code or adding some comments, I'm new to all this, and really want to understand it through out.

**Comment by ponyatov** [comment] 2018-02-06 05:45
The topmost problem you will be faced is user-defined functions. Be warned 8-)

**Comment by nikitagupta55** [comment] 2018-02-06 05:47
@ponyatov , I need your advice, in order to do this type of Parsing, i should be going with PLY or any other sort of Parser generator?

**Comment by ponyatov** [comment] 2018-02-06 05:48
It will be great to have some tutorial on implementing AST interpreter shipped with PLY. But I think nobody able or want to do this tutorial.

Trying to do this, I broke my mind on running functions in the specified environment, and jump out to FORTH implementation based on objects.

**Comment by ponyatov** [comment] 2018-02-06 05:51
Maybe we should start this manual on writing interpreters and compilers on this project wiki?
It's the best place to make it, I think.

**Comment by nikitagupta55** [comment] 2018-02-06 05:55
@ponyatov tutorial idea is pretty amazing. I'm ready to do this with you.

**Comment by nikitagupta55** [comment] 2018-02-06 05:59
@ponyatov  Also advise me how do i understand your code through out? I should understand AST and what else?
So, your code is giving me AST, how do i convert the AST to actual output?

**Comment by ponyatov** [comment] 2018-02-06 08:08
Parsers return [AST/parse trees](https://en.wikipedia.org/wiki/Abstract_syntax_tree), its the rule. What next do you want to do? What formats do you need?
If you need to process parsing results, it is a common technique to use [attribute grammar](http://en.wikipedia.org/wiki/Attribute_grammar), and use [annotated tree](http://www.youtube.com/watch?v=queUceGJqh0)s as intermediate program representation. After you got AST from the parser, you can process it using tree and graph walking algorithms thru nest[]ed nodes, and update attributes. Another powerful way is pattern matching, which you can find in [REFAL](http://en.wikipedia.org/wiki/Refal) language, but I myself have no experience in implementing REFAL engine for object graphs (and very interested in it).

**Comment by nikitagupta55** [comment] 2018-02-06 08:17
@ponyatov,

The functions in the expression's will return a list, For eg let's say all the below mentioned functions in the expression returns some list:

1.) (func1(b) INTERSECT func1(c)) UNION func2(a)

-> ([a,b,c,d] INTERSECT [b,c]) UNION [2,r,t,w,a]
-> [b,c] UNION [2,r,t,w,a]
-> [b,c,2,r,t,w,a] . [ final output will be some list after performing all the set operations in the expression]

**Comment by ponyatov** [comment] 2018-02-06 09:28
So you need not a syntax-driven translation, but direct syntax-driven source execution/interpretation. So you can easily replace the code in grammar rules does what you need, and pass intermediate data via p[] containers between rules.

You mean these `func's()` were defined somewhere in Python and available in runtime, and you want to call them by name? You can do it using `eval()` function, or use some python reflection method to get a pointer to function via its name, and then call it with actual data. 

Are where their parameters stored? A parser will look parameters as strings, and you need some method to bind the string to an actual variable stored in python runtime. It's again a reflection must be.

```
# variable
a=1.23
# func def
import math
def func2(x): return math.sin(x)

class AST: 
...

# variable
a=1.23
# func def
import math
def func2(x): return math.sin(x)

class AST:
...

def p_ex_FN(p):
    'ex : ID LP ex RP '
    try:
        FuncName = p[1].val
        Param = eval(p[3].val)
        Result = eval('%s(%s)'%(FuncName,Param))
        p[0] = AST("python",Result)
    except: # fallback for non-evaluable p[1](p[3])
        p[0] = p[1] << p[3] 
        p[1]['type']='function' ; p[3]['parameter']=True

```
In result you will get AST with **partially computed** nodes:
```
<OP:UNION>
	<OP:INTERSECT>
		<ID:func1>,type = function
			<ID:b>,parameter = True
		<ID:func1>,type = function
			<ID:c>,parameter = True
	<python:0.942488801932>
```

**Comment by ponyatov** [comment] 2018-02-06 09:30
If you define all operators code in grammar rules, you don't need AST at all -- use only floating numbers in `p[]`

**Comment by nikitagupta55** [comment] 2018-02-06 09:57
@ponyatov , I will prefer to write all operator codes in the grammar rules in that case:
So, the rules will look something like 
expression -> expression OP expression
expression -> func1(expression) OP expression | func2(expression) OP
expression | expression | func3(expression) OP expression
expression -> func1(expression) | func2(expression) | func3(expression)
expression -> (expression)
expression -> name
**OP -> UNION | INTERSECT | MINUS | + | * | -**

By operator codes you mean the symbols or exactly what?

Also, in that case how my lexer and parser code will look like if i do not want to use AST thing at all.

**Comment by nikitagupta55** [comment] 2018-02-06 10:07
@ponyatov , yes you are right, those functions will be already defined somewhere in another python program or may be in the same file. We will pass the parameter to that function, on the basis of which those functions will return a list.

So, how will the lexer/parser know about the functions and the parameters?


Can you provide some help, with a simple example. My grammar rules looks good or any change is required???

**Comment by ponyatov** [comment] 2018-02-06 12:26
Need full source to adapt

**Comment by nikitagupta55** [comment] 2018-02-06 19:04
@ponyatov : Detailed description 

I have these 3 functions in some file abc.py (but can be put anywhere according to the convinience):
def func1(param):
     list1=['a','b','c','d']
     return list1

def func2(param):
     list2=[''b','c']
     return list2

def func3(param):
     list3=[2,'r','t','w','a']
     return list3

Now, lets say I have some input expression like below for which I have to implement the lexer and parser using PLY : 

Sample input expression :  

(func1(param1) INTERSECT func2(param2)) UNION func3(param3)

How it should be executed steps : 

Step -1 : lexer should identify all the tokens
Step -2 : In parser the function calls should be made and SET operations should be performed and result should be returned.

 For eg: the above input input expression should be executed in parser as follows:

-> ([a,b,c,d] INTERSECT [b,c]) UNION [2,r,t,w,a]
-> [b,c] UNION [2,r,t,w,a]
-> [b,c,2,r,t,w,a] {this list should be returned as the final result when the parser is executed.

Grammar rules to be used by parser which I think should be fine for these kind of sample expressions are:

expression -> expression OP expression
expression -> func1(expression) OP expression | func2(expression) OP
                        expression | expression | func3(expression) OP expression
expression -> func1(expression) | func2(expression) | func3(expression)
expression -> (expression)
expression -> name
OP -> UNION | INTERSECT | MINUS 


Hope, it makes complete sense now. Can you help accordingly now?

**Comment by nikitagupta55** [comment] 2018-02-07 11:29
@ponyatov can you help according to the last description?

**Comment by dabeaz** [comment] 2018-02-07 11:31
Note: There are many examples of using PLY in the PLY/examples directory.

**Comment by nikitagupta55** [comment] 2018-02-07 11:39
@dabeaz @ponyatov  Is this the right way to tokenize functions and their parameters for the expression below: 

(func1(param1) & func2(param2)) | func3(param3)

import ply.lex as lex
tokens = (  
        'OP',
        'LPAREN',
        'RPAREN',
        'func1',
        'func2',
        'func3',
        'PARAM'
)

# Regular expression rules for simple tokens
t_LPAREN  = r'\('
t_RPAREN  = r'\)'
t_PARAM = r'[a-zA-Z0-9]+'

def t_newline(t):
    r'\n+'
    t.lexer.lineno += len(t.value)

# A string containing ignored characters (spaces and tabs)
t_ignore = ' \t\r\n'

def t_OP(t):
    r'&|-|\|'
    return t

def t_ func1(t):
    r'func1'
    return t

def t_ func2(t):
    r'func2'
    return t

def t_ func3(t):
    r'func3'
    return t

def t_error(t):
    print("Illegal character '%s'" % t.value[0])
    t.lexer.skip(1)

# Build the lexer
lexer = lex.lex()

# Test it out
data = '''

(func1(param1) & func2(param2)) | func3(param3)
'''
lexer.input(data)

# Tokenize
while True:
    tok = lexer.token()
    if not tok: 
        break      # No more input
    print(tok)

**Comment by nikitagupta55** [comment] 2018-02-07 18:20
@dabeaz I do not find any examples which have "function calls" in the input expression

**Comment by nikitagupta55** [comment] 2018-02-08 00:59
This thing helped me : FuncName = p[1].val
        Param = eval(p[3].val)
        Result = eval('%s(%s)'%(FuncName,Param))


I did it 👍

**Comment by nikitagupta55** [comment] 2018-02-09 23:07
@ponyatov @dabeaz 

How to lex and yacc a SET in ply python?

My SET will contain strings or numbers anything like below :

{'a123','b','c','d'}

tokens = (  

        'LIST_ITEM',
        'SET_LPAREN',
        'SET_RPAREN',
        'COMMA'
)

LIST_ITEM = r'\".*?\"'
t_SET_LPAREN = r'\{'
t_SET_RPAREN = r'\}'
t_COMMA = r','
Do, i have to include anything else in my LEX?

BNF Grammar for this SET has to be something very simple like below, for now i have to just identify an expression as SET :

expression -> SET

**Comment by dabeaz** [comment] 2018-02-15 18:08
Closing.  Question pertains to usage of PLY, not a bug in the implementation.

**Closed by dabeaz** 2018-02-15 18:08 UTC

**Comment by nikitagupta55** [comment] 2018-02-16 01:19
@ponyatov @dabeaz 

Can you please look at the below question, its related to comma ambiguity.

https://stackoverflow.com/questions/48818662/ambiguity-in-parsing-comma-as-a-operator-using-ply-python
